---
# Ansible Galaxy roles.
- src: geerlingguy.certbot
  version: 3.0.2
- src: geerlingguy.java
  version: 1.9.4
- src: geerlingguy.jenkins
  version: 3.6.0
- src: geerlingguy.git
  version: 2.0.3
- src: geerlingguy.nginx
  version: 2.6.1
- src: geerlingguy.security
  version: 1.7.0
- src: geerlingguy.firewall
  version: 2.4.1
- src: geerlingguy.pip
  version: 1.2.2
- src: geerlingguy.php-versions
  version: 3.0.0
- src: geerlingguy.php
  version: 3.7.0
- src: geerlingguy.composer
  version: 1.7.3
